version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/index.html
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
